spring.datasource.url=jdbc:h2:mem:ventas_test;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.cloud.discovery.enabled=false
eureka.client.enabled=false

usuario.service.url=http://localhost:8081/api/usuarios
estado.service.url=http://localhost:8083/api/estados
producto.service.url=http://localhost:8084/api/productos
bodega.service.url=http://localhost:8085/api/productos_ubicaciones