CREATE DATABASE IF NOT EXISTS bd_estado;
CREATE DATABASE IF NOT EXISTS bd_producto;
CREATE DATABASE IF NOT EXISTS bd_usuarios;
CREATE DATABASE IF NOT EXISTS bd_direccion;
CREATE DATABASE IF NOT EXISTS bd_bodega;
CREATE DATABASE IF NOT EXISTS bd_ventas;
CREATE DATABASE IF NOT EXISTS bd_envios;
CREATE DATABASE IF NOT EXISTS bd_configuracion;