name: Pipeline para proyecto zenvok

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Verifica contenido del repositorio
      run: |
        echo "Este es el contenido del repositorio"
        tree
      
    - name: Set up JDK 21
      uses: actions/setup-java@v6
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Compilando y Ejecutando Test Unitarios
      run: mvn -B package --file bodega/pom.xml

    - name: Resultado
      run: |
        echo "Build y Pruebas Unitarias Exitosas"